baseurl      = "cw13.github.io"
title        = "C Wilkinson Software"
languageCode = "en-gb"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[ author ]
name = "C Wilkinson Software Ltd"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Services And Blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "C Wilkinson Software Services And Blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "C Wilkinson Software"
    subtitle = "C Wilkinson Software Services And Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
# [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"

[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

[[params.social]]
    name = "email"
    url  = "mailto:c.h_w@icloud.com"

[[params.social]]
    name = "github"
    url  = "https://github.com/cph-w"

[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/callum-haughtey-wilkinson-0089a2179/"

[params.footer]
    trademark = true
    author = true
